version : "3.8"

services:
  api:
    build: .
    image: baerhere/dotnetapi
    ports: 
      - 5000:5000
    working_dir: /api
    volumes:
      - ./api:/api
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
